# Site settings
author: OBIBINIBAA
title: WHY I DECIDED TO STUDY SOFTWARE ENGINEERING
header-img: img/home-bg.png
email: alegnalawn2@yahoo.com
copyright_name: OBIBINIBAA
description: > # this means to ignore newlines until "baseurl:"
  Passion meets Profession
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  angieappiah

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
